AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  IgPostExtractor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions
      Handler: ig_post_extractor.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          # Local environment variables
          AWS_REGION: ap-southeast-1
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource:
                - "arn:aws:bedrock:ap-southeast-1::foundation-model/amazon.nova-micro-v1:0"
                - "arn:aws:bedrock:ap-southeast-1:838835070561:inference-profile/apac.amazon.nova-micro-v1:0"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
