name: Lambda CD Pipeline
permissions:
  id-token: write

on:
  push:
    branches: [ development ]
  workflow_dispatch:


env:
  AWS_REGION: ap-southeast-1
  S3_BUCKET: ig-post-extractor-artifact
  LAMBDA_NAME: IgPostExtractor

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials with OIDC
      # use OpenID Connect (OIDC) to authenticate with AWS to avoid
      # storing AWS credentials as long-lived GitHub secrets.
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy Lambda Function
      id: deploy
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: ${{ env.LAMBDA_NAME }}
        code-artifacts-dir: src/functions/
        s3-bucket: ${{ env.S3_BUCKET }}
        s3-key: functions/"$(date +%Y%m%d%H%M%S)-${{ github.sha }}"
        handler: ig_post_extractor.lambda_handler
        runtime: python3.12
